listen_addresses = '*'
effective_cache_size = 12GB
synchronous_commit = off
shared_buffers = 4GB
work_mem = 20MB
maintenance_work_mem = 2GB
autovacuum_work_mem = 8GB
wal_level = minimal
checkpoint_timeout = 45min
max_wal_size = 10GB
checkpoint_completion_target = 0.9
max_wal_senders = 0
random_page_cost = 1.0